version: "3"

services:
  ai-api:
    build: ./
    environment:
      - VIRTUAL_HOST=ai.api.fmo-dev.com
      - VIRTUAL_PORT=8000
    networks:
      - proxy
    
networks:
   proxy:
      external:
         name: reverse-proxy_proxy
